---
- name: Создание Сети
  community.docker.docker_network:
    name: app_network
    driver: overlay

- name: Выкладка сервиса
  include: "../services/{{ item }}/service.yml"
  Vars:
    - name: "{{ item }}"
  loop: "{{ services }}"