---
- name: deploy / build server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      tags: deploy
    - role: build
      tags: build

- name: managers servers
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig

- name: workers servers
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig