---
- name: deploy server
  hosts: deploy
  roles:
    - role: preconfig
  #  - swarm_init

- name: managers servers
  hosts: managers
  roles:
    - role: preconfig
    - role: deploy
      tags: deploing
      test: 0
   # - swarm_join

- name: workers servers
  hosts: workers
  roles:
    - role: preconfig
  #  - swarm_join