---
- name: deploy server
  hosts: deploy
  roles:
    - role: preconfig
      tags: 
        - universe
  #  - deploy
  #  - swarm_init

- name: managers servers
  hosts: managers
  roles:
    - role: preconfig
      tags: universe
   # - swarm_join

- name: workers servers
  hosts: workers
  roles:
    - role: preconfig
      tags: universe
  #  - swarm_join