---
- name: deploy server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      tags: deploing
      test: 0
  #  - swarm_init

- name: managers servers
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      tags: deploing
      test: 0    
   # - swarm_join

- name: workers servers
  hosts: workers
  roles:
    - role: preconfig
    - role: deploy
      tags: deploing
      test: 0
  #  - swarm_join