---
- name: deploy / build server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    #- role: build
    #  tags: build
    #- role: deploy
    #  tags: deploy
    - role: swarm_init
      tags: swarm_init

- name: managers servers
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    #- role: swarm_join
    #  tags: swarm_join

- name: workers servers
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig
    #- role: swarm_join
    #  tags: swarm_join