---
- name: deploy / build server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: swarm_init
      tags: swarm_init
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    - role: swarm_leave
      node_name: s5c22i5nzql7krrjt8u1sy9at
      tags: swarm_leave

- name: managers servers
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    - role: swarm_join
      type: manager
      tags: swarm_join

- name: workers servers
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig
    - role: swarm_join
      type: worker
      tags: swarm_join