---
- name: Preconfig
  hosts: cluster
  tasks:
    - name: Docker Installing block
      block:

        - name: add repo univers
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Installing additional packets
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: yes
            cache_valid_time: 86400

        - name: Adding key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg

        - name: Add Docker Repository
          apt_repository:
            repo: >
              deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: yes
            filename: docker

        - name: Installing docker-ce
          apt:
            name: docker-ce
            update-cache: yes

        - name: Check docker after installing
          service:
            name: docker
            state: restarted
            enabled: yes
      become: yes

    - name: installing docker-compose
      block:
        - name: Getting latest docker-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Installing docker-compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 'a+x'
            force: yes
      become: yes

    - name: finish installing
      block:
        - name: add user to docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

        - name: reboot server
          reboot:
      become: yes