- name: Add nodes
  var:
    token: "{{ lookup('file', '../../tokens/token-{{ type }}') }}"
  community.docker.docker_swarm:
    state: join
    join_token: "{{ token }}"
    remote_addrs: "{{ advertise_addr }}"