---
- name: "[{{ name }}] Конфигурация секрета"
  include_tasks: "../secret.yml"

- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}{{ name }}:{{ version }}"
        state: present
        networks:
        - name: "{{ networkName }}"
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"