---
- name: Init a new swarm with default parameters
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

#- name: Print token
#  debug:
#    var: token

- name: Наличие директории
  file:
    path: ./tokens
    state: directory
    delegate_to: localhost

- name: Сохранение токена managers
  copy:
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"
    delegate_to: localhost

- name: Сохранение токена worker
  copy:
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
    delegate_to: localhost