---
- name: "[{{ name }}] Создаем секрет"
  vars:
    envFile: "{{ lookup('template', '{{ name }}/.env.j2') | b64encode }}"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ envFile | b64encode}}"
    labels:
      secret: "{{ envFile | hash('sha1') }}"
    data_is_b64: true
    state: present

- name: "Debug"
  vars:
    envFile: "{{ lookup('template', '{{ name }}/.env.j2') | b64encode }}"
  debug:
    msg: "{{ envFile }}"