---
- name: "[{{ name }}] Создаем секрет"
  include_tasks: "./secret-create.yml"

  rescue:
    - name: Удаляем сервис
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "[{{ name }}] Создаем секрет"
      include_tasks: "./secret-create.yml"