---
- name: "[{{ name }}] Создаем секрет"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ lookup('file', './api/.env') | b64encode }}"
    labels:
      secret: "{{ lookup('file', './api/.env') | hash('sha1') }}"
    data_is_b64: true
    state: present